<?php if(Mage::getStoreConfig('solute_tracking/tracking_data/enable')){ ?>
    <script>
        soluteConversionTracking({
            VALUE: "<?php echo $this->escapeHtml( $this->getOrderTotal() ) ?>",
            ORDER_ID: "<?php echo $this->escapeHtml( $this->getOrderId() ) ?>",
            FACTOR: "1",
        });
        function soluteConversionTracking(data) {
            var ttl = 1000*60*60*24*30;
            var a = localStorage.getItem("soluteclid");
            if (!a) return;
            var b = a.split(" ", 2);
            if (parseInt(b[0])+ttl > (new Date()).getTime()) {
                var url = "https://cmodul.solutenetwork.com/conversion";
                url += "?val=" + encodeURIComponent(data.VALUE);
                url += "&oid=" + encodeURIComponent(data.ORDER_ID);
                url += "&factor=" + encodeURIComponent(data.FACTOR);
                url += "&url=" + encodeURIComponent(b[1]);
                var req = new XMLHttpRequest();
                req.open("GET", url);
                req.send();
            } else {
                localStorage.removeItem("soluteclid");
            }
        }
    </script>
<?php } ?>

